spring:
  application:
    name: msa-invoices
  datasource:
    url: jdbc:postgresql://localhost:5432/invoices_db
    username: invoices
    password: invoices
    driver-class-name: org.postgresql.Driver
